name: Udaconnect Persons - Package with Docker

on:
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./modules/persons-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nembo009/udaconnect-persons-api:latest